|
#cloud-config
ssh_pwauth: True
chpasswd:
  list: |
     @@{CRED.username}@@:@@{CRED.secret}@@
  expire: False
users:
  - name: @@{CRED.username}@@
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
