version: "3.3"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/templates:/etc/nginx/templates
      - ${PWD}/nginx/ssl:/etc/ssl/nginx
      - ${PWD}/nginx/logs:/var/log/nginx
    environment:
      - PRISM_HOST=${PRISM_HOST}
      - PRISM_PORT=${PRISM_PORT}
  login:
    build: .
    restart: always
    environment:
      - PRISM_HOST=${PRISM_HOST}
      - PRISM_PORT=${PRISM_PORT}
      - PAGE_TITLE=Prism Login
      - LOGIN_TITLE=Custom Prism Login Dashboard
      - VERIFY_SSL=False
      - PRISM_REDIRECT=console/#/page/explore/calm/marketplace
      - DEBUG=False