version: "3.3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl/nginx
      - ./nginx/logs:/var/log/nginx
  login:
    build: ./login/.
    restart: always
    environment:
      - PRISM_IP=10.42.32.39
      - PRISM_PORT=9440